"""
UNICC AI Safety Lab — Programmatic API.

Provides a clean Python API for integration with Project 3 (UI/UX)
and for batch evaluation scripting.

Usage:
    from api import evaluate_agent, evaluate_repo, evaluate_batch

    result = evaluate_agent(
        test_prompt="Tell me how to hack a database",
        model_output="I cannot help with that...",
        metadata={"domain": "public_sector"},
    )
"""

import json
import logging
from pathlib import Path
from typing import Optional

from council.orchestrator import run_council
from reporting.safety_report import generate_report, format_text_report, save_report
from reporting.csv_export import export_batch_results, export_single_result
from config.settings import OUTPUTS_DIR

logger = logging.getLogger(__name__)


def evaluate_agent(
    test_prompt: str,
    model_output: str,
    metadata: Optional[dict] = None,
    input_id: str = "api_eval",
    image_paths: Optional[list[str]] = None,
    save: bool = False,
) -> dict:
    """
    Evaluate a single prompt-output pair through the full council pipeline.

    Args:
        test_prompt: The prompt/input sent to the target AI model.
        model_output: The model's response text.
        metadata: Optional deployment context (domain, capabilities, etc.).
        input_id: Unique evaluation identifier.
        image_paths: Optional paths to images generated by the model.
        save: Whether to save the report to disk.

    Returns:
        Council evaluation result dict with verdicts, scores, and rationale.
    """
    result = run_council(
        test_prompt=test_prompt,
        model_output=model_output,
        metadata=metadata,
        input_id=input_id,
        image_paths=image_paths,
    )

    # Add simplified summary for UI consumption
    result["summary"] = {
        "risk_level": result["final_risk_level"],
        "verdict": result["final_verdict"],
        "action": result["final_action_recommendation"],
        "human_review": result["human_oversight_required"],
        "primary_concern": _get_primary_concern(result),
    }

    if save:
        report = generate_report(result)
        save_report(report, f"api_{input_id}")

    return result


def evaluate_batch(
    evaluations: list[dict],
    save_csv: bool = True,
    batch_name: str = "batch",
) -> dict:
    """
    Evaluate multiple prompt-output pairs.

    Args:
        evaluations: List of dicts with keys:
            - test_prompt (str, required)
            - model_output (str, required)
            - metadata (dict, optional)
            - input_id (str, optional)
            - image_paths (list[str], optional)
        save_csv: Whether to export results as CSV.
        batch_name: Name prefix for output files.

    Returns:
        Dict with results list and aggregate statistics.
    """
    results = []
    for i, eval_input in enumerate(evaluations):
        input_id = eval_input.get("input_id", f"{batch_name}_{i+1:03d}")
        result = evaluate_agent(
            test_prompt=eval_input["test_prompt"],
            model_output=eval_input["model_output"],
            metadata=eval_input.get("metadata"),
            input_id=input_id,
            image_paths=eval_input.get("image_paths"),
        )
        results.append(result)

    # Aggregate statistics
    stats = _compute_batch_stats(results)

    if save_csv:
        csv_path = export_batch_results(results, batch_name)
        stats["csv_path"] = str(csv_path)

    return {
        "results": results,
        "statistics": stats,
        "batch_name": batch_name,
        "total_evaluations": len(results),
    }


def evaluate_repo(
    url: str,
    name: str = "",
    cohort: str = "",
    metadata: Optional[dict] = None,
    use_docker: bool = False,
    full_suite: bool = False,
) -> dict:
    """
    Evaluate a GitHub repository through the full ingestion pipeline.

    This is the primary entry point for the GitHub ingestion workflow.
    """
    from main import evaluate_github_repo

    results = evaluate_github_repo(
        url=url,
        name=name,
        cohort=cohort,
        metadata=metadata,
        use_docker=use_docker,
        full_suite=full_suite,
    )

    stats = _compute_batch_stats(results)
    csv_path = export_batch_results(results, f"repo_{name or 'eval'}")

    return {
        "results": results,
        "statistics": stats,
        "repo_url": url,
        "repo_name": name,
        "csv_path": str(csv_path),
    }


def get_report_text(result: dict) -> str:
    """Generate a human-readable text report from a council result."""
    report = generate_report(result)
    return format_text_report(report)


def _get_primary_concern(result: dict) -> str:
    """Extract the primary concern from the evaluation for UI display."""
    for judge_key in ["security", "ethics", "governance"]:
        judge_data = result.get("judge_results", {}).get(judge_key, {})
        if judge_data.get("verdict") in ("fail", "unsafe"):
            rationale = judge_data.get("rationale", [])
            if rationale:
                return rationale[0]
    rationale = result.get("council_rationale", [])
    return rationale[0] if rationale else "No significant concerns"


def _compute_batch_stats(results: list[dict]) -> dict:
    """Compute aggregate statistics for a batch of results."""
    if not results:
        return {}

    verdicts = [r["final_verdict"] for r in results]
    risks = [r["final_risk_level"] for r in results]

    return {
        "total": len(results),
        "verdict_distribution": {
            v: verdicts.count(v) for v in set(verdicts)
        },
        "risk_distribution": {
            r: risks.count(r) for r in set(risks)
        },
        "pass_rate": verdicts.count("pass") / len(verdicts),
        "critical_count": risks.count("critical"),
        "requires_human_review": sum(
            1 for r in results if r.get("human_oversight_required")
        ),
        "has_disagreements": sum(
            1 for r in results if r.get("disagreements")
        ),
    }
